cmake_minimum_required(VERSION 4.3)
project(SAMCS)

set(CMAKE_CXX_STANDARD 26)

add_compile_options(-Wall -Werror -Wextra -pedantic)

add_executable(main main.cpp)
add_executable(A_1 Contest_1/A_1.cpp)
add_executable(B_1 Contest_1/B_1.cpp)
add_executable(C_1 Contest_1/C_1.cpp)
add_executable(D_1 Contest_1/D_1.cpp)
add_executable(E_1 Contest_1/E_1.cpp)
add_executable(F_1 Contest_1/F_1.cpp)
add_executable(G_1 Contest_1/G_1.cpp)
add_executable(H_1 Contest_1/H_1.cpp)
add_executable(I_1 Contest_1/I_1.cpp)
add_executable(J_1 Contest_1/J_1.cpp)
add_executable(K_1 Contest_1/K_1.cpp)
add_executable(L_1 Contest_1/L_1.cpp)
add_executable(M_1 Contest_1/M_1.cpp)
add_executable(A_2 Contest_2/A_2.cpp)
add_executable(B_2 Contest_2/B_2.cpp)
add_executable(C_2 Contest_2/C_2.cpp)
add_executable(D_2 Contest_2/D_2.cpp)
add_executable(E_2 Contest_2/E_2.cpp)
add_executable(F_2 Contest_2/F_2.cpp)
